### PR TITLE
Adding Weblate scripts

### PR DESCRIPTION
**Pull request by ctlaltdieliet**
#### Summary
Adding some scripts that are using the weblate API to give feedback to the i18n-channel
@cwarnermm

### CODE REVIEW

**Comment by neflyte** [comment]
I took a look at this and have a few suggestions:

- In  `double_languages.py`, I suggest marking the duplicate language as disabled/inactive/inaccessible instead of deleting the duplicate outright; this would mitigate accidental deletion
- In `double_languages.py`, I suggest the error handling around deleting a duplicate language be modified to give a reason for a failure
- In `double_languages.py`, the error handling doesn't distinguish between an error hitting the Mattermost webhook and an error deleting a language in Weblate; I suggest the error handling be modified to show a different message in each case
- In `weblate_locks_notify_community.py`, I suggest the error handling around hitting the Mattermost webhook be modified to give a reason for a failure

It looks good otherwise! :smile:

**Comment by cwarnermm** [comment]
Thanks for reviewing this, @neflyte!

**Comment by ctlaltdieliet** [comment]
Hi @neflyte,
thank you for the review. 
I've modified the scripts with your suggestions. Your suggestions made it way much better!

**Review by cwarnermm — APPROVED** [review]
Thank you, @ctlaltdieliet!

**Pull request merged**
